import type { EnneagramType } from "./types";

export const GENERIC_PROMPTS: string[] = [
  "What pattern showed up for you today that you wish you could change?",
  "When did you last feel truly seen by someone? What made it different?",
  "What are you avoiding right now, and what might happen if you faced it?",
  "When do you feel most like yourself? What conditions create that?",
  "What would you do differently today if you weren't afraid of judgment?",
  "Where in your body do you feel stress first? What does it tell you?",
  "What belief about yourself do you hold that might not be entirely true?",
  "Who do you become when you're at your best? What shifts?",
  "What conversation have you been putting off, and why?",
  "If your closest friend described your blind spot, what would they say?",
  "When did you last surprise yourself with your own reaction?",
  "What do you need right now that you're not giving yourself?",
  "What would change if you fully accepted this moment as it is?",
  "When do you catch yourself performing instead of being genuine?",
  "What's the difference between who you are and who you think you should be?",
  "What emotional habit do you fall into most easily?",
  "When was the last time you sat with discomfort instead of fixing it?",
  "What would your younger self think of how you handle conflict now?",
  "What are you holding onto that's no longer serving you?",
  "If you could change one automatic reaction, which would it be?",
  "What does your inner critic say most often? Is it true?",
  "Where do you seek external validation when you could trust yourself?",
  "What boundary do you need to set but haven't?",
  "When do you feel most alive? What's happening in those moments?",
  "What are you grateful for that you usually take for granted?",
  "How do you typically respond when someone needs something you can't give?",
  "What would you do today if you knew you couldn't fail?",
  "What part of yourself do you hide from others? Why?",
  "When do you feel the gap between your ideals and your reality most?",
  "What's one thing you learned about yourself this week?",
];

export const TYPE_PROMPTS: Record<EnneagramType, string[]> = {
  1: [
    "Where did your inner critic show up today? Was its voice helpful or harsh?",
    "What imperfection did you notice and let go of instead of fixing?",
    "When did you feel resentment today? What unspoken need was underneath?",
    "How would you treat today's mistakes if they belonged to a friend?",
    "Where did 'should' drive your actions instead of genuine desire?",
    "What rule did you follow that might not serve you anymore?",
    "When did you relax your standards today? How did it feel?",
    "What would you do differently if perfection weren't the goal?",
    "Where did you notice all-or-nothing thinking today?",
    "How did you handle something going 'wrong' today?",
    "When did you feel genuinely playful or spontaneous?",
    "What part of yourself are you judging right now?",
    "Where did you choose compassion over correction today?",
    "What would 'good enough' look like for your current project?",
    "How do you express anger? What would healthy anger look like?",
    "When did you impose your standards on someone else today?",
    "What would happen if you let something be messy?",
    "Where do you need to forgive yourself?",
    "What brings you joy that has nothing to do with improvement?",
    "How can you be right without being rigid?",
    "What would your life look like if you trusted others more?",
    "When did you feel at peace with how things are?",
    "What needs to be good enough today instead of perfect?",
    "Where are you confusing your preferences with moral imperatives?",
    "What emotion are you converting into frustration?",
    "How did you practice self-acceptance today?",
    "When did you choose flexibility over principle?",
    "What would you do if there were no right answer?",
    "Where did you find beauty in imperfection today?",
    "How are you growing beyond your inner critic?",
  ],
  2: [
    "What did you do for yourself today, not for anyone else?",
    "When did you help someone without being asked? What motivated it?",
    "What need of yours went unmet because you were focused on others?",
    "How did you feel when someone didn't need your help?",
    "When did you say 'yes' when you meant 'no'?",
    "What would you ask for if you knew the answer would be yes?",
    "Where did pride show up in your giving today?",
    "How do you feel about receiving help from others?",
    "When did you feel truly appreciated today?",
    "What boundary would make your life easier?",
    "How do you know when your generosity has strings attached?",
    "What do you need that you're not willing to admit?",
    "When did you feel resentful about something you volunteered to do?",
    "What would happen if you let someone struggle without rescuing them?",
    "How do you feel when you're alone with no one to care for?",
    "Where are you giving from fullness versus giving from emptiness?",
    "What relationship feels one-sided right now?",
    "How did you nurture yourself today?",
    "When did you let someone else take care of things?",
    "What would you do if nobody needed you today?",
    "How do you feel about people who are self-sufficient?",
    "What's the difference between your needs and others' expectations?",
    "When did you feel loved without having to earn it?",
    "What would it look like to help without keeping score?",
    "How do you respond when your help is rejected?",
    "What emotion do you hide behind helpfulness?",
    "Where do you need to receive instead of give?",
    "What would radical self-care look like for you today?",
    "How are you learning to value yourself beyond what you do for others?",
    "When did you feel genuinely connected without doing anything?",
  ],
  3: [
    "When did you pause today instead of rushing to the next goal?",
    "What did you do that nobody will ever see or praise you for?",
    "Where did you adapt your personality to fit the room?",
    "What would you do today if achievement didn't matter?",
    "When did you feel like yourself instead of performing a role?",
    "What failure are you avoiding facing?",
    "How did you measure your worth today, and was that fair?",
    "What emotion did you push aside to stay productive?",
    "When did you compare yourself to someone else today?",
    "What would success look like if nobody was watching?",
    "How do you feel when you're not being productive?",
    "What truth about yourself are you packaging for others?",
    "When did you choose depth over efficiency today?",
    "What would happen if you admitted you don't have it all together?",
    "Where are you confusing your image with your identity?",
    "How did you connect with someone authentically today?",
    "What do you want, separate from what others expect?",
    "When did you sit with a feeling instead of accomplishing something?",
    "What would 'enough' look like right now?",
    "How do you feel about rest that's genuinely unproductive?",
    "What part of your story do you never tell?",
    "When did you show vulnerability today?",
    "What would change if you valued being over doing?",
    "How do you handle moments when you can't win?",
    "What relationship do you have that isn't transactional?",
    "Where do you need to slow down?",
    "What does authentic self-expression look like for you?",
    "How are you growing beyond the need for applause?",
    "When did you choose connection over competition?",
    "What would it mean to be loved for who you are, not what you do?",
  ],
  4: [
    "What ordinary moment brought you unexpected beauty today?",
    "When did you notice yourself longing for something others have?",
    "What emotion did you stay with instead of amplifying?",
    "How would today look through the eyes of gratitude?",
    "When did you connect with someone instead of withdrawing?",
    "What's actually here right now that's worth appreciating?",
    "Where did melancholy serve you today, and where did it hold you back?",
    "How did you express your creativity today?",
    "When did you feel misunderstood? What did you actually need?",
    "What would happen if you stopped looking for what's missing?",
    "How do you feel about being ordinary?",
    "What story are you telling about yourself that keeps you stuck?",
    "When did you take action despite not feeling inspired?",
    "What would self-acceptance look like today?",
    "Where do you romanticize suffering instead of addressing it?",
    "How did you show up for someone else today?",
    "What emotion did you feel that you didn't need to analyze?",
    "When did you choose presence over longing?",
    "What's the difference between depth and drama in your life?",
    "How do you feel about people who seem content with simplicity?",
    "What would it look like to belong without being unique?",
    "When did you find meaning in routine today?",
    "What would change if you trusted that you're enough as you are?",
    "How do you handle joy? Do you let it last?",
    "What's one thing about your life right now that's genuinely good?",
    "Where are you creating suffering that doesn't need to exist?",
    "When did you feel at home in yourself today?",
    "What practical step can you take toward something you want?",
    "How are you growing beyond the need to be different?",
    "What would it mean to simply be, without the need for intensity?",
  ],
  5: [
    "When did you share something with someone instead of keeping it to yourself?",
    "What experience did you fully participate in today?",
    "Where did you retreat into thinking when feeling was needed?",
    "How did you use your energy today? Was the rationing necessary?",
    "When did you feel connected to your body?",
    "What would happen if you engaged before you felt fully prepared?",
    "Where did you choose connection over solitude today?",
    "How do you feel when someone needs more from you than you planned to give?",
    "What emotion did you notice that surprised you?",
    "When did you let someone see the real you?",
    "What would happen if you trusted your ability to handle demands?",
    "How did you contribute beyond just thinking today?",
    "When did you feel generous with your time or presence?",
    "What do you know in your body that your mind hasn't caught up to?",
    "Where are you hoarding resources that you actually have enough of?",
    "How did you show up physically in the world today?",
    "What would it look like to need someone without losing yourself?",
    "When did you choose to stay instead of withdrawing?",
    "What question are you using to avoid taking action?",
    "How do you feel about vulnerability?",
    "What would change if you trusted that the world won't deplete you?",
    "When did you feel emotionally alive today?",
    "What would happen if you shared your expertise freely?",
    "How do you express love? Is it visible to others?",
    "Where do you substitute observation for participation?",
    "What simple pleasure did you enjoy today?",
    "When did you surprise yourself by being present?",
    "What boundary is protecting you versus isolating you?",
    "How are you growing in your capacity for engagement?",
    "What would it mean to be fully in your life, not watching from the side?",
  ],
  6: [
    "What did you trust today without needing certainty first?",
    "When did anxiety speak, and what was underneath it?",
    "Where did you find genuine safety inside yourself?",
    "How did you respond to uncertainty today?",
    "When did you act on courage despite fear?",
    "What worst-case scenario did you imagine that didn't happen?",
    "Where are you looking for security outside yourself?",
    "How did you support someone else's confidence today?",
    "When did you question authority constructively?",
    "What decision are you avoiding because you want more certainty?",
    "How do you feel when there's no clear plan?",
    "What would happen if you trusted yourself more?",
    "When did you notice suspicion coloring your perception?",
    "What would courage look like in your current situation?",
    "Where did loyalty serve you today, and where did it limit you?",
    "How do you test whether someone is trustworthy?",
    "What belief about danger is worth questioning?",
    "When did you feel calm in your body today?",
    "What would happen if the thing you fear most actually happened?",
    "How do you feel about ambiguity?",
    "What inner authority did you access today?",
    "When did you choose faith over fear?",
    "What would change if you didn't need to prepare for everything?",
    "How do you differentiate between intuition and anxiety?",
    "Where are you projecting your fears onto others?",
    "What brings you genuine peace?",
    "When did you feel supported without needing to prove loyalty first?",
    "What would it mean to rest in uncertainty?",
    "How are you learning to trust your own judgment?",
    "What would your life look like if you weren't managing fear?",
  ],
  7: [
    "What uncomfortable feeling did you stay with today instead of escaping?",
    "When did you choose depth over novelty?",
    "What plan did you start but didn't finish, and why?",
    "How would today look if you slowed down by half?",
    "When did boredom arise? What were you avoiding underneath it?",
    "What would happen if you fully committed to just one thing?",
    "Where did you reframe pain as positive when it needed to just be felt?",
    "How did you practice satisfaction with what's here?",
    "When did you listen fully instead of planning your next thing?",
    "What limitation taught you something today?",
    "How do you feel about being still with nothing planned?",
    "What pain are you running from right now?",
    "When did you choose focus over stimulation today?",
    "What would 'enough' feel like right now?",
    "Where did your optimism serve you, and where did it gloss over reality?",
    "How did you practice patience today?",
    "What are you afraid you'll feel if you stop moving?",
    "When did you complete something you started?",
    "What would happen if you let yourself be sad?",
    "How do you feel about commitment?",
    "What would change if you didn't need to keep your options open?",
    "When did you experience genuine contentment today?",
    "What routine brought you more than you expected?",
    "How do you handle disappointment?",
    "Where are you scattering energy that could be focused?",
    "What simple thing were you grateful for today?",
    "When did you choose presence over anticipation?",
    "What would it look like to find joy in depth instead of breadth?",
    "How are you growing in your capacity to sit with darkness?",
    "What would it mean to be at peace without needing excitement?",
  ],
  8: [
    "When did you show vulnerability instead of strength today?",
    "What did you control today that might not have needed controlling?",
    "Where did you soften instead of pushing?",
    "How did your intensity affect someone you care about?",
    "When did you let someone else lead?",
    "What would happen if you showed your tender side?",
    "Where did you use power to protect versus power to dominate?",
    "How did you respond to feeling out of control today?",
    "When did you ask for help instead of doing it yourself?",
    "What would vulnerability look like in your closest relationship?",
    "How do you feel about needing others?",
    "What did you defend today that didn't need defending?",
    "When did you choose gentleness?",
    "What would happen if you let your guard down completely?",
    "Where did you mistake assertion for aggression?",
    "How did you protect someone's dignity today?",
    "What emotion lives beneath your anger?",
    "When did you feel safe enough to be soft?",
    "What would justice look like without force?",
    "How do you feel about being seen as weak?",
    "What would change if you trusted others with your heart?",
    "When did you feel tenderness today?",
    "What boundary served protection and what served isolation?",
    "How do you express love beyond providing and protecting?",
    "Where did you yield today? How did it feel?",
    "What would it mean to lead through openness?",
    "When did you respect someone's autonomy instead of directing them?",
    "What softness in yourself are you learning to trust?",
    "How are you growing beyond the need to be invulnerable?",
    "What would it mean to be powerful and tender at the same time?",
  ],
  9: [
    "What did you want today that you didn't voice?",
    "When did you merge with someone else's agenda instead of following your own?",
    "What decision did you avoid, and what would happen if you made it now?",
    "How did you show up for yourself today, not just for others?",
    "When did you feel your own anger or frustration?",
    "What would happen if you said exactly what you think?",
    "Where did you numb out instead of engaging?",
    "How did you prioritize your own needs today?",
    "When did you feel genuinely energized and present?",
    "What conflict are you avoiding, and what's at stake?",
    "How do you feel when someone asks 'What do you want?'",
    "What would you do if you couldn't keep the peace?",
    "When did you take a strong position on something today?",
    "What matters to you that you've been minimizing?",
    "Where did you go along to get along when you shouldn't have?",
    "How did you express yourself directly today?",
    "What would happen if you let people be uncomfortable?",
    "When did you choose action over inertia today?",
    "What's the difference between real peace and just avoiding conflict?",
    "How do you feel about taking up space?",
    "What would change if you fully owned your preferences?",
    "When did you feel your own desires clearly?",
    "What passive resistance did you notice in yourself?",
    "How do you handle being the center of attention?",
    "Where are you sleepwalking through life?",
    "What brings you alive?",
    "When did you set a boundary today?",
    "What would it look like to pursue your own goals fiercely?",
    "How are you growing in your capacity to assert yourself?",
    "What would it mean to be at peace AND fully engaged?",
  ],
};

export function getDailyPrompt(
  type: EnneagramType | null,
  date: Date = new Date()
): string {
  const day = date.getDate() - 1; // 0-indexed
  if (type) {
    const prompts = TYPE_PROMPTS[type];
    return prompts[day % prompts.length];
  }
  return GENERIC_PROMPTS[day % GENERIC_PROMPTS.length];
}
