import type { EnneagramType } from "./types";

/**
 * First-person "I..." statements for each Enneagram type.
 * Used by the "Does This Resonate?" checklist component.
 * 10 behavioral statements per type describing core patterns.
 */
export const RESONANCE_STATEMENTS: Record<EnneagramType, string[]> = {
  1: [
    "I notice mistakes before I notice what is working.",
    "I hold myself to standards that others find unreasonable.",
    "I feel a quiet irritation when people take shortcuts.",
    "I rewrite emails multiple times before sending them.",
    "I have an inner voice that constantly evaluates whether I am doing things correctly.",
    "I find it hard to relax because there is always something that could be improved.",
    "I feel personally responsible when something goes wrong, even if it was not my fault.",
    "I suppress my anger because I believe good people should not get angry.",
    "I often think about the right way to do things long after the moment has passed.",
    "I feel guilty when I take a break, as though rest needs to be earned.",
  ],
  2: [
    "I can sense what other people need before they say it.",
    "I feel most valuable when someone relies on me for help.",
    "I have trouble saying no, even when I am already stretched thin.",
    "I remember small details about the people I care about.",
    "I sometimes feel resentful that my own needs go unnoticed.",
    "I adjust who I am depending on who I am with.",
    "I give compliments and do favors without being asked.",
    "I feel anxious when I think someone might not like me.",
    "I have difficulty identifying what I actually want, separate from what others need.",
    "I tend to take care of everyone else before taking care of myself.",
  ],
  3: [
    "I measure my worth by what I have accomplished.",
    "I instinctively adjust my presentation to impress the people around me.",
    "I feel uncomfortable with downtime that does not lead to something productive.",
    "I keep a mental scoreboard of how I compare to my peers.",
    "I can quickly read a room and figure out what success looks like there.",
    "I struggle to distinguish between who I am and the image I project.",
    "I get restless when I am not working toward a clear goal.",
    "I avoid showing vulnerability because it feels like weakness.",
    "I would rather not start something than risk failing at it publicly.",
    "I catch myself embellishing stories to make myself look better.",
  ],
  4: [
    "I feel things more deeply than the people around me seem to.",
    "I am drawn to beauty, sadness, and meaning in ways others find unusual.",
    "I often feel like something essential is missing from my life.",
    "I withdraw when I feel misunderstood, which happens often.",
    "I compare myself to others and feel that they have something I lack.",
    "I find ordinary, everyday life difficult to engage with fully.",
    "I am drawn to melancholy music, art, or stories, and they feel like home.",
    "I sometimes push people away to test whether they will come back.",
    "I feel most alive when I am in the grip of an intense emotion.",
    "I resist being categorized because I believe my experience is uniquely my own.",
  ],
  5: [
    "I need significant time alone to recharge after social interaction.",
    "I would rather observe a situation than participate in it.",
    "I feel drained when people make unexpected demands on my time or energy.",
    "I prepare extensively before entering a new situation.",
    "I tend to replace emotional experiences with intellectual analysis.",
    "I compartmentalize my life, keeping different areas strictly separate.",
    "I often know the answer but choose not to speak up in a group.",
    "I minimize my needs so that I do not have to depend on anyone.",
    "I feel more comfortable with ideas than with people.",
    "I instinctively pull back when someone gets too close, emotionally or physically.",
  ],
  6: [
    "I mentally rehearse worst-case scenarios before making decisions.",
    "I question authority, but I also look for someone trustworthy to follow.",
    "I notice potential dangers that other people seem to overlook.",
    "I test people's loyalty before I fully trust them.",
    "I second-guess my own decisions, even after I have made them.",
    "I feel a constant low-level anxiety that I cannot always explain.",
    "I am drawn to groups and communities that provide a sense of belonging.",
    "I oscillate between trusting and doubting my own judgment.",
    "I am more aware of what could go wrong than what could go right.",
    "I prepare for problems that may never happen, and I feel safer for it.",
  ],
  7: [
    "I start planning my next adventure before the current one is over.",
    "I reframe negative experiences into positive ones almost automatically.",
    "I find it very difficult to sit with painful emotions for long.",
    "I keep my options open because commitment feels like a trap.",
    "I am energized by new ideas, people, and possibilities.",
    "I tend to overcommit because everything sounds interesting.",
    "I get restless and bored when life becomes too routine.",
    "I use humor to deflect when conversations get too heavy.",
    "I struggle to finish projects because a newer, more exciting one appears.",
    "I avoid thinking about limitations, endings, or things I cannot change.",
  ],
  8: [
    "I trust my gut instincts more than other people's opinions.",
    "I feel a strong urge to protect people who cannot protect themselves.",
    "I take up space in a room without intending to.",
    "I have little patience for people who beat around the bush.",
    "I would rather be respected than liked.",
    "I instinctively test people to see if they will stand their ground.",
    "I feel uncomfortable when I am not in control of a situation.",
    "I express anger openly and directly, sometimes before I realize it.",
    "I see vulnerability as a liability that others will exploit.",
    "I find it easy to make big decisions quickly, while others deliberate.",
  ],
  9: [
    "I go along with what others want to avoid conflict.",
    "I have trouble knowing what I actually want or feel.",
    "I can see all sides of an argument, which makes it hard to take a position.",
    "I numb out with distractions when life gets too intense.",
    "I merge with other people's emotions and priorities without realizing it.",
    "I procrastinate on things that matter to me while staying busy with things that do not.",
    "I minimize my own needs and tell myself they are not important.",
    "I feel invisible in groups, even when I want to be seen.",
    "I stubbornly resist being pushed, but in a passive way that frustrates others.",
    "I would rather keep the peace than say something that might upset someone.",
  ],
};
